=== eWangsf/XMLHomework/whatsup/view/CD/cd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="MusicProduct" type="productType"/>
	<xs:complexType name="productType">
		<xs:sequence>
			<xs:element name="MusicCount" type="xs:nonNegativeInteger"/>
			<xs:element name="Music" type="CDtype" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CDtype">
		<xs:sequence>
			<xs:element name="MusicNumber" type="CDidtype"/>
			<xs:element name="bigPicture" type="xs:string"/>
			<xs:element name="smallPicture" type="xs:string"/>
			<xs:element name="Album" type="xs:string"/>
			<xs:element name="Singer" type="singer"/>
			<xs:element name="Song" type="song"/>
			<xs:element name="Language" type="language"/>
			<xs:element name="Price" type="xs:double"/>
			<xs:element name="Popularity" type="popularity"/>
			<xs:element name="Storage" type="xs:int"/>
			<xs:element name="Publisher" type="xs:string"/>
			<xs:element name="Dealer" type="xs:string"/>
			<xs:element name="Description" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="UploadDate" type="uploadDate" use="required"/>
	</xs:complexType>
	<xs:simpleType name="language">
		<xs:restriction base="xs:string">
			<xs:enumeration value="华语"/>
			<xs:enumeration value="粤语"/>
			<xs:enumeration value="日语"/>
			<xs:enumeration value="韩语"/>
			<xs:enumeration value="英语"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CDidtype">
		<xs:restriction base="xs:string">
			<xs:pattern value="CD-\d+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="singer">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="Sex" type="sex"/>
			<xs:element name="Area" type="area"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="area">
		<xs:restriction base="xs:string">
			<xs:enumeration value="大陆"/>
			<xs:enumeration value="港台"/>
			<xs:enumeration value="日韩"/>
			<xs:enumeration value="欧美"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="sex">
		<xs:restriction base="xs:string">
			<xs:enumeration value="男"/>
			<xs:enumeration value="女"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="song">
		<xs:sequence>
			<xs:element name="Item" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="popularity">
		<xs:restriction base="xs:string">
			<xs:pattern value="\*{0,6}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="uploadDate">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{4}-\d{2}-\d{2}"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== eWangsf/XMLHomework/whatsup/view/CD/cd.xml
<?xml version="1.0" encoding="UTF-8"?>
<MusicProduct xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cd.xsd">
	<MusicCount>30</MusicCount>
	
	
	
<Music UploadDate="2014-6-15"><MusicNumber>CD-9</MusicNumber><bigPicture>../CD_img/2-b.jpg</bigPicture><smallPicture>../CD_img/2-s.jpg</smallPicture><Album>21</Album><Singer><Name>阿黛尔</Name><Sex>女</Sex><Area>欧美</Area></Singer><Song><Item>Rolling In The Deep</Item><Item>Rumour Has It</Item><Item>Turning Tables</Item><Item>Don\'t You Remember</Item><Item>Set Fire To The Rain</Item><Item>He Won\'t Go</Item><Item>Take It All</Item><Item>I\'ll Be Waiting</Item><Item>One And Only</Item><Item>Lovesong</Item></Song><Language>英语</Language><Price>39.10</Price><Popularity>****</Popularity><Storage>298</Storage><Publisher>无</Publisher><Dealer>星外星唱片</Dealer><Description>《阿黛尔:21》格莱美最佳流行女歌手完美蜕变，灵魂天后登顶之作。2011、2012销售冠军，全球销量突破2700万，再造全球十七国排行冠军经典！收录“Rolling In The Deep”、“Someone Like You”两首全球大热金曲。阿黛尔是全球独立音乐巨擘Beggars Group旗下XL Recordings厂牌的歌手，2012年被美国《人物》评选为全球最美女性第14位。曾获得第51届格莱美年度最佳新人，最佳流行女歌手、第54届格莱美年度最佳流行歌手等荣誉，也是首位全英音乐奖评审团奖的得主。专辑《21》在全球销量突破2700万张，荣获第54届格莱美年度最佳专辑以及最佳流行器乐演奏，其中“Rolling In The Deep”获得年度最佳歌曲以及年度最佳制作奖。</Description></Music><Music UploadDate="2014-6-15"><MusicNumber>CD-10</MusicNumber><bigPicture>../CD_img/4_b.jpg</bigPicture><smallPicture>../CD_img/4_s.jpg</smallPicture><Album>红</Album><Singer><Name>泰勒史薇芙特</Name><Sex>女</Sex><Area>欧美</Area></Singer><Song><Item>State Of Grace</Item><Item>Red</Item><Item>Treacherous</Item><Item>I Knew You Were Trouble</Item><Item>All Too Well</Item><Item>22</Item><Item>I Almost Do</Item><Item>Stay Stay Stay</Item><Item>The Last Time</Item><Item>Begin Again</Item></Song><Language>英语</Language><Price>47.40</Price><Popularity>***</Popularity><Storage>100</Storage><Publisher>无</Publisher><Dealer>无</Dealer><Description>《泰勒史薇芙特:红》今年排行榜最流行的顏色：RED！创下全球2200万张专辑与5000万张数字下载单曲佳绩6座格莱美奖认证乡村吉他小天后。</Description></Music><Music UploadDate="2014-6-15"><MusicNumber>CD-11</MusicNumber><bigPicture>../CD_img/5_b.jpg</bigPicture><smallPicture>../CD_img/5_s.jpg</smallPicture><Album>电影配乐代表辑</Album><Singer><Name>久石让</Name><Sex>男</Sex><Area>日韩</Area></Singer><Song><Item>Nausicaa</Item><Item>Princess Mononoke</Item><Item>The Genera</Item><Item>Raging Men</Item><Item>Hana-Bi</Item><Item>Kids Return</Item><Item>Let The Bullets Fly </Item><Item>Howl\'s Moving Castle</Item><Item>One Summer\'s Day</Item><Item>Summer</Item><Item>Villain</Item></Song><Language>日语</Language><Price>49.80</Price><Popularity>*****</Popularity><Storage>980</Storage><Publisher>无</Publisher><Dealer>星外星唱片</Dealer><Description>《久石让:电影配乐代表辑》东京国际会议中心举行“久石让3·11慈善演奏会”现场演出音源。为日本以及亚洲等首屈一指电影巨作配乐的金奖音乐大师久石让于2011年6月9日在东京特别为东日本大震灾慈善演出。与闻名世界之电影导演北野武、宫崎骏携手合作，从日本、亚洲到全球，一代电影配乐大师久石让之生涯代表作精选。包括《风之谷》《龙猫》《Summer》《让子弹飞》《恶人》等影展佳作配乐全13首收录，演出曲目与同年7月“久石让交响音乐会北京站”相同。</Description></Music><Music UploadDate="2014-6-15"><MusicNumber>CD-12</MusicNumber><bigPicture>../CD_img/6_b.jpg</bigPicture><smallPicture>../CD_img/6_s.jpg</smallPicture><Album>左岸香颂</Album><Singer><Name>小野丽莎</Name><Sex>女</Sex><Area>日韩</Area></Singer><Song><Item>C’EST SI BON 如此美好</Item><Item>RêVER 做梦</Item><Item>LES FEUILLES MORTES 枯叶</Item><Item>LES PARAPLUIES DE CHERBOURG 天生一对</Item><Item>J’AI VU 我见过</Item><Item>SALADE DE FRUITS 水果沙拉</Item><Item>WATCH WHAT HAPPENS 看看会发生什么</Item><Item>ELLE， LUI， NOUS 她，他，我们</Item><Item>DANS MON ÎLE 在我的小岛</Item><Item>POUR TOI 给你</Item></Song><Language>日语</Language><Price>51.70 </Price><Popularity>****</Popularity><Storage>186</Storage><Publisher>无</Publisher><Dealer>星外星唱片</Dealer><Description>《小野丽莎:左岸香颂》专辑除Pierre Barouh之外，可说邀请到国际级豪华制作群。要特别提出来的，是法国音乐巨擘、高龄86岁的享利萨瓦多（Henri Salvador）先生，他以成熟甘美的嗓音献唱自己的畅销作J\'AI VU（专辑第5首）。而以名曲Les Parapluies（天生一对）及La Vie en Rose（玫瑰人生）享誉法国的手风琴鬼才Richard Galliano先生，让我们听见他充满个人色彩的演奏技巧。而专辑交织着华丽的弦乐编制格局，是编曲家Mario Adent先生的概念，让整张专辑呈现出洒脱而优雅的乐音。Mario曾为巴西首席的圣保罗交响乐团编曲，因此他的弦乐编曲技术可说获得至高的评价。</Description></Music><Music UploadDate="2014-6-15"><MusicNumber>CD-13</MusicNumber><bigPicture>../CD_img/7_b.jpg</bigPicture><smallPicture>../CD_img/7_s.jpg</smallPicture><Album>1st Mini Album MAMA</Album><Singer><Name>EXO-M</Name><Sex>男</Sex><Area>日韩</Area></Singer><Song><Item>MAMA</Item><Item>What Is Love</Item><Item>HISTORY</Item><Item>你的世界 (Angel)</Item></Song><Language>韩语</Language><Price>31.80</Price><Popularity>**</Popularity><Storage>10</Storage><Publisher>无</Publisher><Dealer>天凯唱片</Dealer><Description>《EXO-M:1st Mini Album MAMA》EXO的名字的由来是从太阳系外行星的EXOPLANET获得灵感，其代表含义为来自未知世界的新星。如同组合的名字，EXO将从独特的音乐、充满力量的舞台表演以及时尚造型三个方面在KPOP热潮中引起新的旋风。</Description></Music><Music UploadDate="2014-6-15"><MusicNumber>CD-15</MusicNumber><bigPicture>../CD_img/8_b.jpg</bigPicture><smallPicture>../CD_img/8_s.jpg</smallPicture><Album>1986-1996 十年精选</Album><Singer><Name>崔健</Name><Sex>男</Sex><Area>大陆</Area></Singer><Song><Item>一无所有</Item><Item>解决</Item><Item>花房姑娘</Item><Item>不是我不明白</Item><Item>新长征路上的摇滚</Item><Item>这儿的空间</Item><Item>快让我在雪地上撒点野</Item><Item>宽容</Item></Song><Language>华语</Language><Price>31.00 </Price><Popularity>****</Popularity><Storage>141</Storage><Publisher>中国国际广播音像出版社</Publisher><Dealer>京文唱片</Dealer><Description>《崔健：1986-1996 十年精选》好的歌曲可以用时间证明，中国过去十年间最激动人心的摇滚乐：《一无所有》、《花房姑娘》、《假行僧》、《新长征路上的摇滚》……80年代青年的信仰、反抗、困惑和激情统统集结在他的音乐空间里！你的怀旧情绪将在此宣泄！</Description></Music><Music UploadDate="2014-6-15"><MusicNumber>CD-16</MusicNumber><bigPicture>../CD_img/9_b.jpg</bigPicture><smallPicture>../CD_img/9_s.jpg</smallPicture><Album>生无所求</Album><Singer><Name>汪峰</Name><Sex>男</Sex><Area>大陆</Area></Singer><Song><Item>上千个黎明</Item><Item>存在</Item><Item>多么完美的生活</Item><Item>不能停止的哭泣</Item><Item>让我们在一起</Item><Item>宝贝 没什么</Item><Item>地心</Item><Item>我们的爱情</Item><Item>有些事我们永远无法左右</Item><Item>不能接受的事实</Item></Song><Language>华语</Language><Price>22.50</Price><Popularity>**</Popularity><Storage>13</Storage><Publisher>无</Publisher><Dealer>星文文化</Dealer><Description>《汪峰:第9张创作大碟 生无所求》是汪峰的全新创作大碟，2CD精包装，一次性收录26首汪峰新作品。在音乐创作上，汪峰更无顾忌，用他的清醒、良知和一贯的人文关怀，写变革中的大时代背景音乐。这在华语乐坛是第一次，也是中国摇滚乐史上第一张严格意义上的双专辑。</Description></Music><Music UploadDate="2014-6-15"><MusicNumber>CD-17</MusicNumber><bigPicture>../CD_img/10_b.jpg</bigPicture><smallPicture>../CD_img/10_s.jpg</smallPicture><Album>神的孩子都在跳舞</Album><Singer><Name>五月天</Name><Sex>男</Sex><Area>港台</Area></Singer><Song><Item>孙悟空 </Item><Item>垃圾车 </Item><Item>倔强</Item><Item>小护士 </Item><Item>让我照顾你</Item><Item>约翰蓝侬</Item><Item>回来吧</Item><Item>错错错</Item><Item>晚安 地球人</Item><Item>超人</Item><Item>神的孩子都在跳舞</Item><Item>圣诞夜惊魂</Item><Item>垃圾车</Item></Song><Language>华语</Language><Price>27.10</Price><Popularity>*****</Popularity><Storage>1000</Storage><Publisher>辽宁广播电视音像出版社</Publisher><Dealer> 广州娱通文化传播有限公司</Dealer><Description>《五月天：神的孩子都在跳舞》第五张第五张专辑，堪称最五月天的创作，专辑最大的特色是五人都有创作收录其中，本质上更是抛开束缚，回归五月天，找回从前玩band的快乐，这次他们也在隔了四年后，重回第二张专辑《爱情万岁》时位于富士山下河口湖的录音室，相同的环境，一样五天70万的租金，不同的是携带的乐器暴涨3倍，总价超过150万，还因搭机超重被罚10万元，当然最不一样的是五人音乐上的成长，使五月天更能自由于音乐中。在我活的地方，我就是我自己的神，每个人都在做自己相信应该要做的事，就像我跳舞。 </Description></Music><Music UploadDate="2014-6-15"><MusicNumber>CD-18</MusicNumber><bigPicture>../CD_img/11_b.jpg</bigPicture><smallPicture>../CD_img/11_s.jpg</smallPicture><Album>生还者</Album><Singer><Name>余文乐</Name><Sex>男</Sex><Area>港台</Area></Singer><Song><Item>生还者</Item><Item>南拳</Item><Item>雷霆伞兵</Item><Item>护卫</Item><Item>人民英雄</Item><Item>生还者</Item><Item>坚强</Item></Song><Language>粤语</Language><Price>19.70</Price><Popularity>****</Popularity><Storage>197</Storage><Publisher>珠影白天鹅音像出版社</Publisher><Dealer>环球唱片有限公司</Dealer><Description>《生还者》是余文乐推出的第三张专辑。这位刚出道时被称为“谢霆锋接班人”的小天王终于再次向乐坛发起攻击。专辑同名主打歌“生还者”在2004年的香港新城劲爆颁奖典礼上就已得过奖，公司还专门请来曾为贝克汉姆、中田英寿、藤原纪香等拍广告的日籍名导演Rage拍摄了MV，描述了一对因火灾而相识相爱的恋人，从火灾后的身体生还到女友失聪后两人的爱情生还，让人领悟“生还”的更深层感动。为了配合唱片主题，较早前阿乐与歌迷到荒山进行探险旅程，这些旅程片段也都收录在这张专辑内。</Description></Music><Music UploadDate="2014-6-15"><MusicNumber>CD-19</MusicNumber><bigPicture>../CD_img/12_b.jpg</bigPicture><smallPicture>../CD_img/12_s.jpg</smallPicture><Album>轶事 Tales</Album><Singer><Name>陈柏宇</Name><Sex>男</Sex><Area>港台</Area></Singer><Song><Item>死神来了</Item><Item>毫无余地</Item><Item>倒流</Item><Item>测谎机</Item><Item>I Wanna Fly</Item><Item>黑马王子</Item></Song><Language>粤语</Language><Price>56.00 </Price><Popularity>***</Popularity><Storage>130</Storage><Publisher>上海文艺音像电子出版社</Publisher><Dealer>环球唱片有限公司</Dealer><Description>《陈柏宇:轶事》7年型格大蜕变，陈柏宇最真诚剖白。陈柏宇全新专辑《轶事》再度发挥创作宇宙，创作多首全新作品。联同著名作曲人冯翰铭Alex Fung、恭硕良Jun Kung &amp; 倪凯民Kelvin Avon及蓝奕邦Pong Nan制作。继“矛盾大对决”后另一主打歌“Baby Don\'t Cry”紧贴推介。专辑中，Jason希望跟乐迷分享更多自己对于生活或社会等不同事情的睇法，所以不论音乐或歌词上，都贯注很多Jason最私有的情感在内，乐迷在听歌之余，也可以听到有关Jason的小故事，或是Jason的心底话，专辑名字《Tales》亦由此而来。今次在《Tales》中，Jason将进一步强化他的唱作人身份，参与了5首歌曲的创作部份，并找来恭硕良（Jun Kung）、Kelvin Avon、冯翰铭及何山携手监制新碟，令新碟的音乐性更强更有惊喜！</Description></Music><Music UploadDate="2014-6-15"><MusicNumber>CD-20</MusicNumber><bigPicture>../CD_img/13_b.jpg</bigPicture><smallPicture>../CD_img/13_s.jpg</smallPicture><Album>夏狂热</Album><Singer><Name>苏打绿</Name><Sex>男</Sex><Area>港台</Area></Singer><Song><Item>掌声落下</Item><Item>他夏了夏天</Item><Item>（口白：英文诗）</Item><Item>包围</Item><Item>御花园</Item><Item>彼得与狼</Item><Item>无眠</Item><Item>狂热</Item><Item>煽动</Item><Item>近未来</Item><Item>蝉想</Item><Item>（口白：英文诗）</Item></Song><Language>华语</Language><Price>48.00</Price><Popularity>****</Popularity><Storage>234</Storage><Publisher>北京东方影音公司</Publisher><Dealer>星外星唱片</Dealer><Description>《苏打绿:夏狂热》夏天就该狂热自己的模样，苏打绿带给大家《夏狂热》。“韦瓦第四季狂想”第二弹，来自英伦的狂热摇滚，用生命力谱就的华彩乐章！温暖春天轻拂后，紧接着夏天，苏打绿将带给大家热情的摇滚。英国，终年的浓雾孕育出无数世界知名摇滚乐团：The Beatles，Pink Floyd，The Who，Deep Purple，Radiohead，Oasis，Blur，Coldplay……苏打绿前往伦敦，录制一张单纯、直接、用音符炙热生命的计划中第二张专辑《夏狂热》。2009年发行的《夏狂热》这张专辑从音乐制作、配唱、母带后期处理，苏打绿的造型、拍照、MV全数都在英国伦敦进行，做出来的成果，非常具有爆发力跟速度感。专辑里的时间，是跳动的，不是一天的流动，而是生命中，过去到现在、现在到未来的流逝。“狂热”一如字面上的意义，就是直接、执着。“狂热”就是这张专辑的终极精神，十一首歌都在表达某一种狂热，并皆以直接的字汇呈现。一如夏天的热情，狂热的直接，专辑定调为摇滚风格，所有的发想皆以摇滚的概念为基础。</Description></Music><Music UploadDate="2014-6-16"><MusicNumber>CD-21</MusicNumber><bigPicture>../CD_img/14_b.jpg</bigPicture><smallPicture>../CD_img/14_s.jpg</smallPicture><Album>Read Me</Album><Singer><Name>薛凯琪</Name><Sex>女</Sex><Area>港台</Area></Singer><Song><Item>慕容雪</Item><Item>叮叮车</Item><Item>噗噗跳</Item><Item>苏州河</Item><Item>最近我爱上了Lily Allen</Item></Song><Langua
